FROM almalinux:9

RUN dnf install -y bash findutils tar gzip procps-ng \
  && dnf clean all

COPY tests /tests
COPY fixtures/keys/id_ed25519 /tmp/client_key
COPY fixtures/keys/id_ed25519.pub /tmp/client_key.pub

WORKDIR /workspace

CMD ["/bin/bash"]
